services:
  server:
    container_name: ${SERVER_APP_NAME}
    build:
      context: ../../..
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE}
    image: ${SERVER_IMAGE_NAME}:${SERVER_IMAGE_TAG}
    ports:
      - "${SERVER_APP_PORT}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    restart: unless-stopped
